services:
  postgres:
    container_name: "TaskForge-postgres"
    image: "postgres:15"
    restart: always
    ports:
      - "5433:5432"
    environment:
      - "POSTGRES_USER=username"
      - "POSTGRES_DB=taskForge"
      - "POSTGRES_PASSWORD=password"

cache:
  container-name: "TaskForge-redis"
  build: "./session-cache/cache-module"
  restart: always
  ports: -'6379:6379'
