services:
  postgres:
    container_name: "TaskForge-postgres"
    image: "postgres:15"
    restart: always
    ports:
      - "5433:5432"
    environment:
      - "POSTGRES_USER=username"
      - "POSTGRES_DB=taskForge"
      - "POSTGRES_PASSWORD=password"

  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    container_name: elasticsearch
    environment:
      - discovery.types=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xmx512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"

  cache:
    container_name: "TaskForge-redis"
    build: "./session-cache/cache-module"
    restart: always
    ports:
      - "6379:6379"
